class Languages{
    static const Map<String, Map<String, String>> languages = {
    "sv": {
        "name": "Svenska",
        "nativeName": "Svenska",
        "checking_login": "Kontrollerar inloggning...",
        "login": "Logga in",
        "username": "Användarnamn",
        "password": "Lösenord",
        "language": "Språk",
        "theme": "Tema",
        "light": "Ljust",
        "dark": "Mörkt",
        "system": "System",
        "save": "Spara",
        "home": "Hem",
        "settings": "Inställningar",
        "refresh": "Uppdatera",
        "logout": "Logga ut",
        "welcome": "Välkommen till M29 Narvaro",
        "error": "Ett fel inträffade",
        "login_successful": "Inloggning lyckades",
        "welcome_back": "Välkommen tillbaka!",
        "invalid_credentials": "Ogiltiga inloggningsuppgifter",
        "logged_out": "Utloggad",
        "username_required": "Användarnamn krävs",
        "password_required": "Lösenord krävs",
        "login_required": "Inloggning krävs",
        "login_page_title": "Logga in",
        "please_try_again": "Försök igen",
        "select_language": "Välj språk",
        "select_theme": "Välj tema",
        "english": "Engelska",
        "swedish": "Svenska",
        "change_language": "Byt språk",
        "change_theme": "Byt tema",
        "change_theme_and_language": "Byt tema och språk",
        "current_language": "Nuvarande språk",
    },
    "en": {
        "name": "English",
        "nativeName": "English",
        "checking_login": "Checking login...",
        "login": "Login",
        "username": "Username",
        "password": "Password",
        "language": "Language",
        "theme": "Theme",
        "light": "Light",
        "dark": "Dark",
        "system": "System",
        "save": "Save",
        "home": "Home",
        "settings": "Settings",
        "refresh": "Refresh",
        "logout": "Logout",
        "welcome": "Welcome to M29 Narvaro",
        "error": "An error occurred",
        "invalid_credentials": "Invalid login credentials",
        "username_required": "Username is required",
        "password_required": "Password is required",
        "login_successful": "Login successful",
        "login_page_title": "Login",
        "welcome_back": "Welcome back!",
        "logged_out": "Logged out",
        "login_required": "Login required",
        "please_try_again": "Please try again",
        "select_language": "Select language",
        "select_theme": "Select theme",
        "english": "English",
        "swedish": "Swedish",
        "change_language": "Change language",
        "change_theme": "Change theme",
        "change_theme_and_language": "Change theme and language",
        "current_language": "Current language",
    }
  };

  Map<String, String> getLanguage(String code) {
    return languages[code] ?? languages["en"]!;
  }
}